---

- hosts: 

  vars:
    application: photoprism

    docker_network: 

    photoprism_database_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      61663237623563646436316561613165366434373533643030346234303434383931326662313463
      3839343433366331336139396164313735346435623138660a373064316336386463663235663465
      31343238326262653735383931376336323666346333326437613361326233323363653761343066
      6266616563646538360a623538303366646339666264663332623835306366643361393630393136
      39356564643538343132346231656639666637336339656264636361313837643030653336666235
      3433323465663932336233396162336263643134636235643036

    PHOTOPRISM_ADMIN_PASSWORD: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      62396663353661653235313962313337313934336238353035366461323664633862353632636638
      6163623132643932333335323665633934366565323736640a303463353565636138343438313130
      38323432316334356139653239353437616237396663333137326137366230653837616261336130
      3831396434363632360a316165396630373837613032383261613535323037616338333564393166
      35343464303530303333363161333661633631633731326164633532363163336264


  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0777"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: photoprism/photoprism:latest
        state: started
        restart_policy: unless-stopped
        security_opts:
          - seccomp=unconfined
          - apparmor=unconfined
        networks:
        - name: "{{ docker_network }}"      

        env:
          PHOTOPRISM_ADMIN_USER: "admin"
          PHOTOPRISM_ADMIN_PASSWORD: "{{ PHOTOPRISM_ADMIN_PASSWORD }}"

          PHOTOPRISM_PUBLIC: "false"
          PHOTOPRISM_READONLY: "true"

          PHOTOPRISM_ORIGINALS_LIMIT: "5000"
          PHOTOPRISM_HTTP_COMPRESSION: "gzip"
          PHOTOPRISM_LOG_LEVEL: "info"

          PHOTOPRISM_UPLOAD_NSFW: "true"
          PHOTOPRISM_DETECT_NSFW: "false"
          PHOTOPRISM_EXPERIMENTAL: "false"

          PHOTOPRISM_SITE_URL: "https://{{ application }}.{{ common_tld }}/"

          PHOTOPRISM_DATABASE_DRIVER: "mysql"
          PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
          PHOTOPRISM_DATABASE_NAME: "photoprism"
          PHOTOPRISM_DATABASE_USER: "photoprism"
          PHOTOPRISM_DATABASE_PASSWORD: "{{ photoprism_database_password }}"
          PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
         
        working_dir: "/photoprism"
        volumes:
          - "{{ config_directory }}/photoprism:/photoprism/storage"
          - "{{ common_directory_photos }}:/photoprism/originals"
        published_ports:
          - 2342:2342
        labels:
          chadburn.enabled: "true"

          chadburn.job-exec.photoprism-photo-permissions.user: "0"
          chadburn.job-exec.photoprism-photo-permissions.schedule: "@every 1m"
          chadburn.job-exec.photoprism-photo-permissions.command: "sh -c \"chown {{ common_user_id }}:33 -R /photoprism/originals && chmod -R 775 /photoprism/originals\""
          chadburn.job-exec.photoprism-photo-permissions.tty: "false"
          chadburn.job-exec.photoprism-photo-permissions.no-overlap: "true"

          # https://dl.photoprism.org/docker/scheduler/jobs.ini
          ## https://docs.photoprism.org/user-guide/library/originals
          chadburn.job-exec.photoprism-auto-index.user: "0"
          chadburn.job-exec.photoprism-auto-index.schedule: "@hourly"
          chadburn.job-exec.photoprism-auto-index.command: "/opt/photoprism/bin/photoprism index --cleanup"
          chadburn.job-exec.photoprism-auto-index.tty: "false"
          chadburn.job-exec.photoprism-auto-index.no-overlap: "true"

          ## https://docs.photoprism.org/user-guide/organize/video/
          chadburn.job-exec.photoprism-convert.user: "0"
          chadburn.job-exec.photoprism-convert.schedule: "@daily"
          chadburn.job-exec.photoprism-convert.command: "/opt/photoprism/bin/photoprism convert"
          chadburn.job-exec.photoprism-convert.tty: "false"
          chadburn.job-exec.photoprism-convert.no-overlap: "true"

          homepage.group: Document & Files
          homepage.name: Photoprism
          homepage.icon: photoprism.png
          homepage.href: http://staging.xeolab:2342
          homepage.description: Photo server
          homepage.widget.type: photoprism
          homepage.widget.url: http:// http://staging.xeolab:2342
          homepage.widget.username: admin
          homepage.widget.password: "{{ PHOTOPRISM_ADMIN_PASSWORD }}"