---

- hosts: 

  vars:
    application: actualbudget
    docker_network: 

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0771"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: actualbudget/actual-server:24.5.0
        pull: true
        state: started
        restart_policy: always
        published_ports:
          - 5006:5006
        volumes:
          - "{{ config_directory }}:/data"
        networks:
          - name: "{{ docker_network }}"
        labels:
          '{
            "traefik.enable": "true",
            "traefik.http.routers.{{ application }}.rule": "Host(`budget.{{ common_tld }}`)",
            "traefik.http.routers.{{ application }}.entryPoints": "https",
            "traefik.http.services.{{ application }}.loadbalancer.server.scheme": "http",
            "traefik.http.routers.{{ application }}.middlewares": "auth@file",
            "traefik.http.middlewares.test-ratelimit.ratelimit.average": "100|string",
            "traefik.http.middlewares.test-ratelimit.ratelimit.burst": "100|string",
            "traefik.http.middlewares.test-ratelimit.ratelimit.sourcecriterion.ipstrategy.excludedips": "127.0.0.1/32, 172.16.0.0/24",
          }'
