---

- hosts: 

  vars:
    application: adminer
    docker_network: 

  tasks:
    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: adminer:4.8.1
        state: started
        restart_policy: unless-stopped
        published_ports:
        - "8282:8080"
        env:
          ADMINER_DEFAULT_SERVER: mariadb
          ADMINER_DESIGN: dracula
        networks:
          - name: "{{ docker_network }}"
        labels:
          '{
            "traefik.enable": "true",
            "traefik.http.routers.{{ application }}.entryPoints": "https",
            "traefik.http.services.{{ application }}.loadbalancer.server.scheme": "http",
            "traefik.http.routers.{{ application }}.middlewares": "auth@file",
          }'