---

- hosts: 

  vars:
    application: agent


  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0775"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: portainer/agent:2.19.4
        pull: true
        state: started
        restart_policy: always
        ports:
        - "9001:9001"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /var/run/docker.sock:/var/run/docker.sock

          - "{{ config_directory }}:/data"
        security_opts:
          - no-new-privileges:true
