---

- hosts: staging

  vars:
    application: agent
    docker_network: staging

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0771"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: portainer/agent:latest
        pull: true
        state: started
        restart_policy: always
        ports:
        - "9001:9001"
        networks:
          - name: "{{ docker_network }}"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - "{{ config_directory }}:/data"
          - /var/run/docker.sock:/var/run/docker.sock
        security_opts:
          - no-new-privileges:true
