---

- hosts: 

  vars:
    application: auto-m4b
    docker_network: 

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0771"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: seanap/auto-m4b:latest
        pull: true
        state: started
        restart_policy: unless-stopped
        env:
          UID: "{{ common_root_id | string }}"
          GID: "{{ common_root_group | string }}"
          TZ: "{{ common_timezone }}"
          CPU_CORES: 2
          SLEEPTIME: 5m
        networks:
          - name: "{{ docker_network }}"
        volumes:
          - "{{ config_directory }}/temp:/temp"
          - "{{ config_directory }}/config:/config"
        security_opts:
          - no-new-privileges:true
