---

- hosts: 

  vars:
    application: chadburn

    docker_network: 

  tasks:
    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: ghcr.io/premoweb/chadburn:1.0.6
        state: started
        restart_policy: unless-stopped
        command:
          - daemon
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
          - name: "{{ docker_network }}"
