---

- hosts: staging

  vars:
    application: cloudflared

    docker_network:
      - name: bridge

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0777"

    # - name: Template cloudflared configs
    #   ansible.builtin.template:
    #     src: "{{ files_directory }}/config.yml.j2"
    #     dest: "{{ config_directory }}/config.yml"
    #     mode: "0440"

    - name: Create container
      ansible.builtin.include_role:
        name: docker_container
      vars:
        image: cloudflare/cloudflared:latest
        hostname: "{{ application }}"
        restart_policy: always
        command: "tunnel --config /home/nonroot/.cloudflared/config.yml run {{ UUID }}"
        volumes:
          - "{{ config_directory }}:/home/nonroot/.cloudflared/"
        networks:
          - name: "{{ docker_network }}"