---

- hosts: 

  vars:
    application: cloudflared
    docker_network:  

  handlers:
    - name: Restart
      community.docker.docker_container:
        name: "{{ application }}"
        restart: true
        comparisons:
          '*': ignore

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0777"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: cloudflare/cloudflared:latest
        state: started
        restart_policy: always
        command: "tunnel --config /home/nonroot/.cloudflared/config.yml run <<UUID>>"
        volumes:
          - "{{ config_directory }}:/home/nonroot/.cloudflared/"
        networks:
          - name: "{{ docker_network }}"