---

- hosts:

  vars:
    application: dockersocket
    docker_network:

  tasks:
    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: tecnativa/docker-socket-proxy:latest
        state: started
        restart_policy: unless-stopped
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
        privileged: true
        env:
          CONTAINERS: 1
          POST: 0
        published_ports:
          - 2375:2375
        networks: "{{ docker_network }}"