---

- hosts: 

  vars:
    application: socket-proxy
    docker_network: 

  tasks:
    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: ghcr.io/tecnativa/docker-socket-proxy:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "2375:2375"
        networks:
          - name: "{{ docker_network }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
        env:
          CONTAINERS: "1" # Allow access to viewing containers
          SERVICES: "1" # Allow access to viewing services (necessary when using Docker Swarm)
          TASKS: "1" # Allow access to viewing tasks (necessary when using Docker Swarm)
          POST: "0" # Disallow any POST operations (effectively read-only)
