---

- hosts: 

  vars:
    application: dozzle

  tasks:
    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: amir20/dozzle:v4.11.5
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "8081:8080"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        healthcheck:
          test: ["CMD", "/dozzle", "healthcheck"]
          interval: 3s
          timeout: 30s
          retries: 5
          start_period: 30s
        env:
          DOZZLE_NO_ANALYTICS: "true"
