---

- hosts: 

  vars:
    application: glances
    docker_network:

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0771"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: nicolargo/glances:3.4.0.2
        state: started
        restart_policy: always
        pid_mode: host
        published_ports:
        - "61208:61208"
        networks:
          - name: "{{ docker_network }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
        env:
          GLANCES_OPT: "-w"
        security_opts:
          - no-new-privileges:true
