---

- hosts: 

  vars:
    application: grafana

    docker_network: 

  handlers:
    - name: Restart
      community.docker.docker_container:
        name: "{{ application }}"
        restart: true
        comparisons:
          '*': ignore

  tasks:

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "472" 
        group: "{{ common_group }}"
        mode: "0771"
      loop:
        - "{{ config_directory }}/provisioning/dashboards"
        - "{{ config_directory }}/provisioning/datasources"
        - "{{ config_directory }}/provisioning/plugins"
        - "{{ config_directory }}/provisioning/notifiers"
        - "{{ config_directory }}/provisioning/alerting"
        - "{{ config_directory }}/data"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: grafana/grafana:11.3.0
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "3000:3000"
        env:
          GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel"
        volumes:
          - "{{ config_directory }}/data:/var/lib/grafana"
          - "{{ config_directory }}/provisioning:/etc/grafana/provisioning"
        networks:
          - name: "{{ docker_network }}"
