---

- hosts: 

  vars:
    application: homepage

    docker_network: 

  handlers:
    - name: Restart
      community.docker.docker_container:
        name: "{{ application }}"
        restart: true
        comparisons:
          '*': ignore

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}/config"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0775"

    - name: Create icons folder
      ansible.builtin.file:
        path: "{{ homepage_icons_remote_dir }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0771"

    - name: Copy icons
      ansible.builtin.copy:
        src: "{{ files_directory }}/icons/"
        dest: "{{ homepage_icons_remote_dir }}/"
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0775"
      notify: Restart

    - name: Create docker socket proxy container
      community.docker.docker_container:
        name: "{{ application }}-docker-socket-proxy"
        image: tecnativa/docker-socket-proxy:0.1.1
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "2375:2375"
        networks:
          - name: "{{ docker_network }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
        env:
          CONTAINERS: "1" # Allow access to viewing containers
          SERVICES: "1" # Allow access to viewing services (necessary when using Docker Swarm)
          TASKS: "1" # Allow access to viewing tasks (necessary when using Docker Swarm)
          POST: "0" # Disallow any POST operations (effectively read-only)

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: ghcr.io/benphelps/homepage:v0.6.35
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "3000:3000"
        networks:
          - name: "{{ docker_network }}"
        volumes:
          - "{{ config_directory }}/config:/app/config"
          - "{{ homepage_icons_remote_dir }}:/app/public/icons"

          - "{{ common_directory_storage }}:{{ common_directory_storage }}:ro"
        env:
          PUID: "{{ common_user_id | string }}"
          PGID: "{{ common_group_id | string }}"
        labels:
          '{
            "traefik.enable": "true",
            "traefik.http.routers.{{ application }}.rule": "Host(`home.{{ common_tld }}`)",
            "traefik.http.routers.{{ application }}.entryPoints": "https",
            "traefik.http.services.{{ application }}.loadbalancer.server.scheme": "http",
            "traefik.http.routers.{{ application }}.middlewares": "auth@file",
          }'
          
