---

- hosts: 

  vars:
    application: homepage

    docker_network: 

  handlers:
    - name: Restart
      community.docker.docker_container:
        name: "{{ application }}"
        restart: true
        comparisons:
          '*': ignore

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}/config"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0775"

    - name: Create docker socket proxy container
      community.docker.docker_container:
        name: docker-socket-proxy
        image: tecnativa/docker-socket-proxy:0.1.1
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "2375:2375"
        networks:
          - name: "{{ docker_network }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
        env:
          CONTAINERS: "1" # Allow access to viewing containers
          SERVICES: "1" # Allow access to viewing services (necessary when using Docker Swarm)
          TASKS: "1" # Allow access to viewing tasks (necessary when using Docker Swarm)
          POST: "0" # Disallow any POST operations (effectively read-only)

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: ghcr.io/gethomepage/homepage:v0.8.4
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "3111:3000"
        networks:
          - name: "{{ docker_network }}"
        volumes:
          - "{{ config_directory }}/config:/app/config"
          - /var/run/docker.sock:/var/run/docker.sock:ro 
        env:
          PUID: "{{ common_user_id | string }}"
          PGID: "{{ common_group_id | string }}"

