---

- hosts: monitoring

  vars:
    application: influxdb-1.8
    docker_network: monitor

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0775"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: influxdb:1.8.10-alpine
        pull: true
        state: started
        restart_policy: always
        volumes:
          - "{{ config_directory }}:/var/lib/influxdb"
        env:
          INFLUXDB_DB: influx
          INFLUXDB_ADMIN_USER: admin
          INFLUXDB_ADMIN_PASSWORD: admin
        published_ports:
          - "8086:8086"
        networks:
              - name: "{{ docker_network }}"
