---

- hosts: 

  vars:
    application: influxdb2
    docker_network: 

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0775"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: influxdb:2.7.1-alpine
        pull: true
        state: started
        restart_policy: always
        volumes:
          - "{{ config_directory }}:/var/lib/influxdb"
        published_ports:
          - "8086:8086"
        networks:
              - name: "{{ docker_network }}"
