---

- hosts: 

  vars:
    application: it-tools
    docker_network: 

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0775"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: corentinth/it-tools:latest
        pull: true
        state: started
        restart_policy: always
        ports:
        - "1180:80"
        volumes:
          - "{{ config_directory }}:/data"
        networks:
          - name: "{{ docker_network }}"
        security_opts:
          - no-new-privileges:true
