---

- hosts: 

  vars:
    application: mealie

    docker_network: 

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0771"

    - name: Create container
      community.docker.docker_container:
        name: docker_container
        image: hkotel/mealie:omni-nightly
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "3000:3000"
          - "9000:9000"
        env:
          PUID: "{{ common_user_id | string }}"
          PGID: "{{ common_group_id | string }}"
          TZ: "{{ common_timezone }}"
          BASE_URL: "https://{{ application }}.{{ common_tld }}"

          ALLOW_SIGNUP: "false"
          RECIPE_PUBLIC: "false"
          RECIPE_DISABLE_COMMENTS: "true"
        volumes:
          - "{{ config_directory }}/data:/app/data"
        networks:
          - name: "{{ docker_network }}"
        labels:
          '{
            "traefik.enable": "true",
            "traefik.http.routers.{{ application }}.rule": "Host(`onboard.{{ common_tld }}`)",
            "traefik.http.routers.{{ application }}.entryPoints": "https",
            "traefik.http.services.{{ application }}.loadbalancer.server.scheme": "http",
            "traefik.http.routers.{{ application }}.middlewares": "auth@file",
          }'