---

- hosts: 

  vars:
    application: mealie
    docker_network: 
    postgres_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      34376434633335666136626365323131313062633265366264383339646339323964376330623366
      6438636165623035363364643636353931336532613463320a393835653465376434313563373764
      61623034353038343161383761626661356538323231653637613965623930373162363730643334
      6230626239363433320a303334323665313262376438336534643534376462303563343662386335
      65306331363036393062623638313434613464393136336165356531336631623661373864303363
      6637303336376164396534653033633761633537353032353733

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0771"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: ghcr.io/mealie-recipes/mealie:v1.6.0
        state: started
        restart_policy: unless-stopped
        env:
          # https://docs.mealie.io/documentation/getting-started/installation/backend-config/

          ## General
          PUID: "{{ common_user_id | string }}"
          PGID: "{{ common_group_id | string }}"
          BASE_URL: "https://{{ application }}.{{ common_tld }}"
          TZ: "{{ common_timezone }}"
          ALLOW_SIGNUP: "false"
          LOG_LEVEL: DEBUG

          ## Database
          DB_ENGINE: postgres
          POSTGRES_USER: "{{ application }}"
          POSTGRES_PASSWORD: "{{ postgres_password }}"
          POSTGRES_SERVER: "{{ host.postgres_host }}"
          POSTGRES_PORT: "{{ host.postgres_port | string }}"
          POSTGRES_DB: "{{ application }}"

          ## Email
          SMTP_HOST: "{{ common_email_host }}"
          SMTP_PORT: "{{ common_email_port | string }}"
          SMTP_FROM_NAME: "{{ application | title }}"
          SMTP_AUTH_STRATEGY: "{{ 'tls' if common_email_protocol == 'tls' else 'ssl' }}"
          SMTP_FROM_EMAIL: "{{ application }}{{ common_email_to }}"
          SMTP_USER: "{{ common_smtp_username }}"
          SMTP_PASSWORD: "{{ common_smtp_password }}"

          ## OpenID Connect (OIDC)
          OIDC_AUTH_ENABLED: "true"
          OIDC_CONFIGURATION_URL: "https://auth.{{ common_tld }}/.well-known/openid-configuration"
          OIDC_CLIENT_ID: "{{ application }}"
          OIDC_AUTO_REDIRECT: "true"
          OIDC_PROVIDER_NAME: "Authelia"
          OIDC_SIGNUP_ENABLED: "true"
          OIDC_USER_CLAIM: "email"
          OIDC_USER_GROUP: users
          OIDC_ADMIN_GROUP: admins
        volumes:
          - "{{ config_directory }}/data:/app/data"
        published_ports:
          - "9000:9000"
        networks:
          - name: "{{ docker_network }}"
        labels:
          '{
            "traefik.enable": "true",
            "traefik.http.routers.{{ application }}.rule": "Host(`mealie.{{ common_tld }}`)",
            "traefik.http.routers.{{ application }}.entryPoints": "https",
            "traefik.http.services.{{ application }}.loadbalancer.server.scheme": "http",
            "traefik.http.routers.{{ application }}.middlewares": "auth@file",
            "traefik.http.middlewares.test-ratelimit.ratelimit.average": "100|string",
            "traefik.http.middlewares.test-ratelimit.ratelimit.burst": "100|string",
            "traefik.http.middlewares.test-ratelimit.ratelimit.sourcecriterion.ipstrategy.excludedips": "127.0.0.1/32, 172.16.0.0/24",
          }'
