---

- hosts: staging

  vars:
    application: nextcloud

    docker_network: staging

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0771"

    - name: Create {{ application }} container
      community.docker.docker_container:
        name: nextcloud-aio-mastercontainer
        image: nextcloud:latest
        state: started
        restart_policy: unless-stopped
        networks:
          - name: "{{ docker_network }}"
        volumes:
          - "{{ config_directory }}:/mnt/docker-aio-config"
          - "{{ common_directory_storage }}:/mnt/ncdata"
          - /var/run/docker.sock:/var/run/docker.sock:ro
        env: 
          AIO_DISABLE_BACKUP_SECTION: "false" 
          APACHE_PORT: "11000" # Is needed when running behind a web server or reverse proxy (like Apache, Nginx and else). See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
          APACHE_IP_BINDING: "127.0.0.1" # Should be set when running behind a web server or reverse proxy (like Apache, Nginx and else) that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
          COLLABORA_SECCOMP_DISABLED: "false" # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature
          NEXTCLOUD_DATADIR: "/mnt/ncdata" # Allows to set the host directory for Nextcloud's datadir. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
          NEXTCLOUD_MOUNT: "/mnt/ "# Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
          NEXTCLOUD_UPLOAD_LIMIT: "10G" # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
          NEXTCLOUD_MAX_TIME: "3600" # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
          NEXTCLOUD_MEMORY_LIMIT: "512M" 
        published_ports:
          - 85:80
          - 8082:8080
          - 4443:8443
        labels:
          # 33 is www-data
          '{
            "chadburn.enabled": "true",
            "chadburn.job-exec.{{ application }}-cron.user": "33",
            "chadburn.job-exec.{{ application }}-cron.schedule": "@every 5m",
            "chadburn.job-exec.{{ application }}-cron.command": "/usr/local/bin/php -f cron.php",
            "chadburn.job-exec.{{ application }}-cron.tty": "false",
            "chadburn.job-exec.{{ application }}-cron.no-overlap": "true"
          }'