---

- hosts: 

  vars:
    application: openldap
    docker_network: 

    organization: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      35393933663066326633613063653539653131303262313063666237363333323333633432366461
      6638323938393166613538313964616336633032326665360a363531373639656235363339373638
      61383864323637353562303930323831333561363931646538353430323231376466353962366361
      6161393665663662380a623032346338356562303565653263626533356362663135653035626364
      6433

  handlers:
    - name: Restart
      community.docker.docker_container:
        name: "{{ application }}"
        restart: true
        comparisons:
          '*': ignore

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "root"
        group: "root"
        mode: "0775"

    - name: Create {{ application }} container
      community.docker.docker_container:
        name: "{{ application }}"
        image: osixia/openldap:1.5.0
        state: started
        restart_policy: always
        published_ports:
        - "389:389"
        - "636:636"
        env:
          LDAP_ORGANISATION: "{{ organization }}"
          LDAP_DOMAIN: "{{ common_local_tld }}"
          LDAP_ADMIN_PASSWORD: "{{ ldap_admin_password }}"
          LDAP_DEBUG: "true"
          LDAP_RFC2307BIS_SCHEMA: "true"
          LDAP_TLS_VERIFY_CLIENT: "never"
        volumes:
          - "{{ config_directory }}/db:/var/lib/ldap"
          - "{{ config_directory }}/config:/etc/ldap/slapd.d"
        networks:
          - name: "{{ docker_network }}"

    - name: Create {{ application }}-user-manager container
      community.docker.docker_container:
        name: lum
        image: wheelybird/ldap-user-manager:v1.11
        state: started
        restart_policy: always
        published_ports:
          - "8383:80"
        env:
          SERVER_HOSTNAME: "lum.{{ common_local_tld }}"

          LDAP_DEBUG: "true"
          LDAP_IGNORE_CERT_ERRORS: "true"
          NO_HTTPS: "true"

          LDAP_URI: "ldap://{{ ldap_host }}"
          LDAP_BASE_DN: "{{ ldap_base_dn }}"

          LDAP_ADMIN_BIND_DN: "{{ ldap_admin_dn }}"
          LDAP_ADMIN_BIND_PWD: "{{ ldap_admin_password }}"
          LDAP_ADMINS_GROUP: "admins"
          
          SMTP_HOSTNAME: "{{ common_email_host }}"
          SMTP_HOST_PORT: "{{ common_email_port | string }}"
          SMTP_USERNAME: "{{ common_email_username }}"
          SMTP_PASSWORD: "{{ common_smtp_password }}"
          SMTP_USE_TLS: "{{ 'TRUE' if common_email_protocol == 'tls' else 'FALSE' }}"
          EMAIL_FROM_ADDRESS: "lum{{ common_email_to }}"
          EMAIL_FROM_NAME: "ldap-user-manager"
        networks:
          - name: "{{ docker_network }}"
