---

- hosts: 

  vars:
    application: overseerr
    docker_network: 

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0771"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: sctx/overseerr:1.33.2
        state: started
        restart_policy: unless-stopped        
        env:
          TZ: "{{ common_timezone }}"
          LOG_LEVEL: debug
        volumes:
          - "{{ config_directory }}:/app/config"
        published_ports:
          - "5055:5055"
        networks:
          - name: "{{ docker_network }}"
        labels:
          '{
            "traefik.enable": "true",
            "traefik.http.routers.{{ application }}.entryPoints": "https",
            "traefik.http.services.{{ application }}.loadbalancer.server.scheme": "http",
            "traefik.http.routers.{{ application }}.middlewares": "crowdsec@file",
          }'