---

- hosts: 

  vars:
    application: peanut
    docker_network: 

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0775"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: brandawg93/peanut:latest
        pull: true
        state: started
        restart_policy: always
        ports:
          - "8585:8080"
        env:
          NUT_HOST: ""
          NUT_PORT: "3493"
          WEB_PORT: "8080"
        networks:
          - name: "{{ docker_network }}"
        security_opts:
          no-new-privileges:true
