---

- hosts: 

  vars:
    application: postgres-exporter
    docker_network: 
    
  tasks:

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: prometheuscommunity/postgres-exporter:v0.15.0
        state: started
        restart_policy: unless-stopped
        published_ports:
          - 9187:9187
        env:
          DATA_SOURCE_NAME: "postgresql://postgres:PASSWORD@localhost:5432/?sslmode=disable"
        volumes:
          - "{{ config_directory }}:/bitnami/"
        networks:
          - name: "{{ docker_network }}"