---

- hosts: 

  vars:
    application: redis
    docker_network: 
    
  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0777"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: bitnami/redis:7.2.4
        state: started
        restart_policy: unless-stopped
        published_ports:
          - 6379:6379
        env:
          REDIS_PASSWORD: "{{ host.redis_password }}"
        volumes:
          - "{{ config_directory }}:/bitnami/"
        networks:
          - name: "{{ docker_network }}"