---

    - hosts: 
    
      vars:
        application: scrutiny
        docker_network: 
    
      handlers:
        - name: Restart
          community.docker.docker_container:
            name: "{{ application }}"
            restart: true
            comparisons:
              '*': ignore
    
      tasks:
        - name: Create config folder
          ansible.builtin.file:
            path: "{{ config_directory }}/config"
            state: directory
            owner: "{{ common_user }}"
            group: "{{ common_group }}"
            mode: "0771"
    
        - name: Template config
          ansible.builtin.template:
            src: "{{ files_directory }}/scrutiny.yaml.j2"
            dest: "{{ config_directory }}/config/scrutiny.yaml"
            mode: "0440"
          notify: Restart
    
        - name: Get disks
          ansible.builtin.shell: for line in $(lsblk --noheadings --list --scsi --output name); do echo "/dev/${line}"; done
          register: lsblk_disks
          changed_when: false
    
        - name: Create container
          community.docker.docker_container:
            name: "{{ application }}"
            image: ghcr.io/analogj/scrutiny:v0.6.0-omnibus
            state: started
            restart_policy: unless-stopped
            env:
              COLLECTOR_CRON_SCHEDULE: "*/5 * * * *"
            capabilities:
              - SYS_RAWIO
            published_ports:
              - "8383:8080"
            volumes:
              - /run/udev:/run/udev:ro
              - "{{ config_directory }}/config:/opt/scrutiny/config"
              - "{{ config_directory }}/influxdb:/opt/scrutiny/influxdb"
            devices: "{{ lsblk_disks.stdout_lines }}"
            networks:
              - name: "{{ docker_network }}"
    