---

- hosts: 

  vars:
    application: telegraf
    docker_network: 

  handlers:
    - name: Restart
      community.docker.docker_container:
        name: "{{ application }}"
        restart: true
        comparisons:
          '*': ignore

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0775"
    
    - name: Template telegraf config
      ansible.builtin.template:
        src: "{{ files_directory }}/{{ item }}.j2"
        dest: "{{ config_directory }}/{{ item }}"
        mode: "0644"
      loop:
        - telegraf.conf
      notify: Restart

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: telegraf:1.30.2
        pull: true
        state: started
        restart_policy: always
        volumes:
          - "{{ config_directory }}/telegraf.conf:/etc/telegraf/telegraf.conf"
        published_ports:
          - "8225:8125"
        networks:
              - name: "{{ docker_network }}"
