---

- hosts: 

  vars:
    application: wizarr
    docker_network: 

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0771"

    - name: Create container
      community.docker.docker_container:
        name: onboard
        image: ghcr.io/wizarrrr/wizarr:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "5690:5690"
        env:
          TZ: "{{ common_timezone }}"
          DISABLE_BUILTIN_AUTH: false | string
          APP_URL: "https://wizarr.{{ common_tld }}"
        networks:
          - name: "{{ docker_network }}"
        volumes:
          - "{{ config_directory }}/database:/data/database"
        labels:
          '{
            "traefik.enable": "true",
            "traefik.http.routers.{{ application }}.entryPoints": "https",
            "traefik.http.services.{{ application }}.loadbalancer.server.scheme": "http",
            "traefik.http.routers.{{ application }}.middlewares": "auth@file",
          }'