---

- hosts: 

  vars:
    application: wizarr
    docker_network: 

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0771"

    - name: Create container
      community.docker.docker_container:
        name: "{{ application }}"
        image: ghcr.io/wizarrrr/wizarr:4.1.0
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "5690:5690"
        env:
          TZ: "{{ common_timezone }}"
          MIN_PASSWORD_LENGTH: "12"
          MAX_PASSWORD_LENGTH: "42"
          MIN_PASSWORD_UPPERCASE: "1"
          MIN_PASSWORD_NUMBERS: "1"
          MIN_PASSWORD_SPECIAL: "1"
          DISABLE_BUILTIN_AUTH: "false"
          APP_URL: "https://onboard.{{ common_tld }}"
        networks:
          - name: "{{ docker_network }}"
        volumes:
          - "{{ config_directory }}/database:/data/database"
        labels:
          '{
            "traefik.enable": "true",
            "traefik.http.routers.{{ application }}.rule": "Host(`onboard.{{ common_tld }}`)",
            "traefik.http.routers.{{ application }}.entryPoints": "https",
            "traefik.http.services.{{ application }}.loadbalancer.server.scheme": "http",
            "traefik.http.routers.{{ application }}.middlewares": "auth@file",
          }'