---

- hosts: 

  vars:
    application: zabbix
    docker_network: 

    postgres_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      34623264643162353662376635313263376337303537386338373564386263376536303635613265
      3064643730653261303466346637663337336330336532370a306333383937623866336635363864
      66343835643931306231313437643432356362366161636238383634663532343432333039643462
      3861343065333137660a303363323337623532633565626637633165633366633832386265303061
      65653766663436356261326235633836306230653837316661316561646235663333376637653335
      3139303865396230343931303737616634386462353032313237

  tasks:
    - name: Create config folder
      ansible.builtin.file:
        path: "{{ config_directory }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: "0775"

    - name: Create {{ application }}-server
      community.docker.docker_container:
        name: "{{ application }}-server"
        image: zabbix/zabbix-server-pgsql:6.0.0-ubuntu
        state: started
        restart_policy: unless-stopped
        published_ports:
          - 10051:10051
        volumes: 
          - "{{ config_directory }}/server-data:/var/lib/zabbix"
          - "{{ config_directory }}/snmptraps-data:/var/lib/zabbix/snmptraps"
          - "{{ config_directory }}/export-data:/var/lib/zabbix/export"
        env:
          DB_SERVER_HOST: 
          POSTGRES_USER: "zabby"
          POSTGRES_PASSWORD: "{{ postgres_password }}"
          POSTGRES_DB: "{{ application }}"
        networks:
          - name: "{{ docker_network }}"

    - name: Create {{ application }}-apache
      community.docker.docker_container:
        name: "{{ application }}-web"
        image: zabbix/zabbix-web-apache-pgsql:7.0.0-ubuntu
        state: started
        restart_policy: unless-stopped
        published_ports:
          - 8686:8080
        volumes: 
          - "{{ config_directory }}/web-data:/usr/share/zabbix"
        env:
          DB_SERVER_HOST: 
          POSTGRES_USER: "zabby"
          POSTGRES_PASSWORD: "{{ postgres_password }}"
          POSTGRES_DB: "{{ application }}"
          ZBX_SERVER_HOST: zabbix-server
          PHP_TZ: "{{ common_timezone }}"
        networks:
          - name: "{{ docker_network }}"

    - name: Create {{ application }}-agent2
      community.docker.docker_container:
        name: "{{ application }}-agent2"
        image: zabbix/zabbix-agent2:6.0.0-ubuntu
        state: started
        restart_policy: unless-stopped
        volumes: 
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        env:
          ZBX_HOSTNAME: ""
          ZBX_SERVER_HOST: zabbix-server
          ZBX_SERVER_PORT: '10051'
          ZBX_SERVER_ACTIVE: zabbix-server
        networks:
          - name: "{{ docker_network }}"