---

- hosts: 

  handlers:
    - name: Restart
      ansible.builtin.service:
        name: smbd
        state: restarted

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false

    - name: Install
      ansible.builtin.apt:
        name: samba
        state: present

    - name: Enable service
      ansible.builtin.service:
        name: smbd
        state: started
        enabled: true

    - name: Create Samba users
      ansible.builtin.command: 
        "smbpasswd -a {{ users.name }} '{{ users.password }}'"
      with_items: 
        "{{ users }}"
    
    - name: Configure
      ansible.builtin.copy:
        content: |
          [global]

            workgroup = WORKGROUP

            log file = /var/log/samba/log.%m
            max log size = 1000
            syslog = 0
            panic action = /usr/share/samba/panic-action %d

          [files]
            comment = ZFS - files
            path = {{ common_directory_storage }}/{{item.name}}
            read only = no
            browseable = yes
            valid users = {{users.name}}

          [Backups]
            comment = Backup save location
            path = {{ common_directory_backup }}/{{item.name}}
            read only = no
            writable = yes
            browseable = yes
            valid users = {{users.name}}

          [Documents]
            comment = Backup save location
            path = {{ common_directory_document }}/{{item.name}}
            read only = no
            writable = yes
            browseable = yes
            valid users = {{users.name}}

        dest: /etc/samba/smb.conf
        validate: "testparm %s --suppress-prompt"
        mode: "0440"
      notify: Restart

    - name: Allow in firewall
      community.general.ufw:
        name: samba
        rule: allow
