---

- hosts: 

  handlers:
    - name: Restart
      ansible.builtin.service:
        name: smbd
        state: restarted

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false

    - name: Install
      ansible.builtin.apt:
        name: samba
        state: present

    - name: Enable service
      ansible.builtin.service:
        name: smbd
        state: started
        enabled: true
    
    - name: Configure
      ansible.builtin.copy:
        content: |
          [global]

            workgroup = WORKGROUP

            log file = /var/log/samba/log.%m
            max log size = 1000
            syslog = 0
            panic action = /usr/share/samba/panic-action %d

          [files]
            comment = ZFS - files
            path = {{ common_directory_storage }}/{{item.name}}
            read only = no
            browseable = yes

        dest: /etc/samba/smb.conf
        validate: "testparm %s --suppress-prompt"
        mode: "0440"
      notify: Restart

    - name: Allow in firewall
      community.general.ufw:
        name: samba
        rule: allow
    
    - name: Reminder
      ansible.builtin.debug:
        msg: Create an smb password using `sudo smbpasswd aedot`
